### ISSUE TITLE
Exception when calling `ol`

### ISSUE THREAD

**Issue by kostecky** [zertrin/clikraken#10] opened 2017-08-09 01:34 UTC
```
Traceback (most recent call last):
  File "~/bin/clikraken", line 11, in <module>
    sys.exit(main())
  File "~/.virtualenvs/clikraken/lib/python3.6/site-packages/clikraken/clikraken.py", line 32, in main
    func(args)
  File "~/.virtualenvs/clikraken/lib/python3.6/site-packages/clikraken/api/private/list_open_orders.py", line 42, in list_open_orders
    ol[otype] = sorted(ol[otype], key=lambda odict: Decimal(odict['price']))
  File "~/.virtualenvs/clikraken/lib/python3.6/site-packages/clikraken/api/private/list_open_orders.py", line 42, in <lambda>
    ol[otype] = sorted(ol[otype], key=lambda odict: Decimal(odict['price']))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

Solution: Indent line 42 in `clikraken/api/private/list_open_orders.py`

**Comment by zertrin** [comment] 2017-08-15 15:02
Hi, thanks for reporting this issue. 

I have been unable to reproduce the issue. Could you give some more details about how you trigger this problem? Which asset pair for example? with what kind of prices?

I would like to apply your proposed solution, but I need to understand _why_ this is the correct solution, and for that it would be best if it was possible to reproduce the issue, or at least know which inputs lead to the issue.

**Comment by ronybarbosa** [comment] 2017-12-09 21:41
I am getting this error. I am running under windows:

Command: clikraken last_trades

Error:

ERROR    - ValueError while querying Kraken API!
Traceback (most recent call last):
  File "c:\users\bkron\appdata\local\programs\python\python36-32\lib\site-packages\clikraken\api\api_utils.py", line 68, in query_api
    res = func(api_method, api_params)
  File "c:\users\bkron\appdata\local\programs\python\python36-32\lib\site-packages\krakenex\api.py", line 148, in query_public
    return self._query(urlpath, req, conn)
  File "c:\users\bkron\appdata\local\programs\python\python36-32\lib\site-packages\krakenex\api.py", line 131, in _query
    return json.loads(ret)
  File "c:\users\bkron\appdata\local\programs\python\python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\bkron\appdata\local\programs\python\python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\bkron\appdata\local\programs\python\python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zertrin** [comment] 2017-12-10 03:24
@ronydj this has nothing to do with this issue. This is just because kraken api is completely overloaded in the past few months and doesn't return correct data very often.

**Comment by zertrin** [comment] 2017-12-10 03:25
I am closing this issue since I have never been able to reproduce it and the OP didn't provide more information.

**Closed as completed** 2017-12-10 03:26 UTC
Labels: not sure if bug or not, more info needed
